//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MothershipLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Comm
    {
        public Client_Comm()
        {
            this.Client_Comm_Line = new HashSet<Client_Comm_Line>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid Client { get; set; }
        public int Type { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual ICollection<Client_Comm_Line> Client_Comm_Line { get; set; }
        public virtual Client Client11 { get; set; }
    }
}
