//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MothershipLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Client_Info = new HashSet<Client_Info>();
            this.Client_Comm1 = new HashSet<Client_Comm>();
            this.Job = new HashSet<Job>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
    
        public virtual Client_Comm Client_Comm { get; set; }
        public virtual ICollection<Client_Info> Client_Info { get; set; }
        public virtual ICollection<Client_Comm> Client_Comm1 { get; set; }
        public virtual ICollection<Job> Job { get; set; }
    }
}
