//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MothershipLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Comm_Line
    {
        public System.Guid CommId { get; set; }
        public int Line { get; set; }
        public string Text { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual Client_Comm Client_Comm { get; set; }
    }
}
