//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MothershipLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime ToExecute { get; set; }
        public Nullable<System.DateTime> Executed { get; set; }
        public System.Guid Client { get; set; }
        public string Command { get; set; }
        public string Response { get; set; }
        public int Status { get; set; }
    
        public virtual Client Client1 { get; set; }
    }
}
