//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MothershipLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MothershipEntities : DbContext
    {
        public MothershipEntities()
            : base("name=MothershipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Command> Command { get; set; }
        public virtual DbSet<Audit> Audit { get; set; }
        public virtual DbSet<Client_Comm> Client_Comm { get; set; }
        public virtual DbSet<Client_Info> Client_Info { get; set; }
        public virtual DbSet<Client_Comm_Line> Client_Comm_Line { get; set; }
        public virtual DbSet<Job> Job { get; set; }
    }
}
