//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MothershipLibrary.ReceiveCommService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MothershipService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] StringArrayValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] StringArrayValue {
            get {
                return this.StringArrayValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringArrayValueField, value) != true)) {
                    this.StringArrayValueField = value;
                    this.RaisePropertyChanged("StringArrayValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReceiveCommService.IReceiveCommService")]
    public interface IReceiveCommService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveCommService/GetData", ReplyAction="http://tempuri.org/IReceiveCommService/GetDataResponse")]
        bool GetData(string[] values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveCommService/GetData", ReplyAction="http://tempuri.org/IReceiveCommService/GetDataResponse")]
        System.Threading.Tasks.Task<bool> GetDataAsync(string[] values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveCommService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IReceiveCommService/GetDataUsingDataContractResponse")]
        MothershipLibrary.ReceiveCommService.CompositeType GetDataUsingDataContract(MothershipLibrary.ReceiveCommService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveCommService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IReceiveCommService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MothershipLibrary.ReceiveCommService.CompositeType> GetDataUsingDataContractAsync(MothershipLibrary.ReceiveCommService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReceiveCommServiceChannel : MothershipLibrary.ReceiveCommService.IReceiveCommService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiveCommServiceClient : System.ServiceModel.ClientBase<MothershipLibrary.ReceiveCommService.IReceiveCommService>, MothershipLibrary.ReceiveCommService.IReceiveCommService {
        
        public ReceiveCommServiceClient() {
        }
        
        public ReceiveCommServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiveCommServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveCommServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveCommServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetData(string[] values) {
            return base.Channel.GetData(values);
        }
        
        public System.Threading.Tasks.Task<bool> GetDataAsync(string[] values) {
            return base.Channel.GetDataAsync(values);
        }
        
        public MothershipLibrary.ReceiveCommService.CompositeType GetDataUsingDataContract(MothershipLibrary.ReceiveCommService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MothershipLibrary.ReceiveCommService.CompositeType> GetDataUsingDataContractAsync(MothershipLibrary.ReceiveCommService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
